package engine

import "core:encoding/uuid"

// Code generated by type_guid_gen. Do not edit.

TypeKey :: enum u16 {
	A,
	AudioSettings,
	B,
	C,
	Camera,
	GameSettings,
	Lifetime,
	Parallel,
	Player,
	PlayerSettings,
	SceneFile,
	Script,
	Sequence,
	SpriteRenderer,
	TextureSettings,
	Transform,
	Tween,
	TweenMoveToLocal,
	TweenRotateToLocal,
	TweenScaleToLocal,
	TweenUnion,
	string,
}

INVALID_TYPE_KEY :: TypeKey(max(u16))

UUID_NIL :: uuid.Identifier{};
A__Guid := uuid.read("f49ac13b-63cc-4374-a567-0e02b2c3d479") or_else UUID_NIL
AudioSettings__Guid := uuid.read("ec017cc2-7267-45b4-ae80-d6861094d27a") or_else UUID_NIL
B__Guid := uuid.read("f50ac13b-63cc-4374-a567-0e02b2c3d479") or_else UUID_NIL
C__Guid := uuid.read("f51ac13b-63cc-4374-a567-0e02b2c3d479") or_else UUID_NIL
Camera__Guid := uuid.read("7a3b9c1d-2e4f-5a6b-8c7d-9e0f1a2b3c4d") or_else UUID_NIL
GameSettings__Guid := uuid.read("f47ac10b-58cc-4372-a567-0e02b2c3d479") or_else UUID_NIL
Lifetime__Guid := uuid.read("c3a1e4f2-7b8d-4a2e-9c5f-1d6e3b0f7a8c") or_else UUID_NIL
Parallel__Guid := uuid.read("916005b6-1c68-49e7-88be-0add6164d3a8") or_else UUID_NIL
Player__Guid := uuid.read("d3f1a2b4-7e8c-4d5f-9a0b-1c2e3f4a5b6c") or_else UUID_NIL
PlayerSettings__Guid := uuid.read("c8b1e4a2-9d3f-4c5e-a6b7-8f1d2e3c4b5a") or_else UUID_NIL
SceneFile__Guid := uuid.read("0d489fce-9c04-4e4d-be12-f3f590d60cea") or_else UUID_NIL
Script__Guid := uuid.read("adaf3551-4704-4255-ad91-fde59441dc53") or_else UUID_NIL
Sequence__Guid := uuid.read("24d46399-b3a0-44e7-abd1-6da5d759e935") or_else UUID_NIL
SpriteRenderer__Guid := uuid.read("b7e2a1c3-5d4f-4e8a-9f1b-3c6d8e0a2b4f") or_else UUID_NIL
TextureSettings__Guid := uuid.read("21d45bcf-2bd8-44db-b780-953c2f8b610f") or_else UUID_NIL
Transform__Guid := uuid.read("312927b7-3c4a-4929-9807-8216baf26a68") or_else UUID_NIL
Tween__Guid := uuid.read("aecaf150-0418-4fed-81a3-708f68ccaa8b") or_else UUID_NIL
TweenMoveToLocal__Guid := uuid.read("da9d301a-66a3-450c-8c0b-8c696ad60b0b") or_else UUID_NIL
TweenRotateToLocal__Guid := uuid.read("b72f3c1a-9e45-4b8d-a3f7-2d1e5c8f0b94") or_else UUID_NIL
TweenScaleToLocal__Guid := uuid.read("aa1970c6-51d2-4d27-9dc8-718ad1e51160") or_else UUID_NIL
TweenUnion__Guid := uuid.read("a243efe5-6e34-4d1c-886c-83928685df48") or_else UUID_NIL
string__Guid := uuid.read("c4f0a1b2-3d5e-6f7a-8b9c-0d1e2f3a4b5c") or_else UUID_NIL
